name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
    paths:
      - apps/api/**
  workflow_dispatch:

jobs:
  push-app-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './apps/api'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for arm64
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/mendableai/firecrawl:latest
          platforms: linux/arm64
